# Generated by Django 2.2.4 on 2020-06-07 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenant', '0004_auto_20200607_1014'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queue_no', models.IntegerField(default=0, verbose_name='Queue Number')),
                ('appointment_date', models.DateField(blank=True, null=True, verbose_name='Appointment Date')),
                ('start_time', models.CharField(max_length=255, verbose_name='Start Time')),
                ('end_time', models.CharField(max_length=255, verbose_name='End Time')),
                ('center', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tenant.Center')),
            ],
        ),
    ]
