# Generated by Django 2.2.4 on 2020-06-07 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0002_auto_20200607_0952'),
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='instance',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='form.Instance'),
        ),
    ]
