# Generated by Django 2.0.2 on 2020-06-05 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(db_index=True, help_text='Organization Name', max_length=255, unique=True)),
                ('code', models.TextField(db_index=True, help_text='Organization Code', max_length=255, unique=True)),
            ],
        ),
    ]
