# Generated by Django 2.0.2 on 2020-06-05 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='code',
            field=models.CharField(db_index=True, help_text='Organization Code', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(db_index=True, help_text='Organization Name', max_length=255, unique=True),
        ),
    ]
