# Generated by Django 3.0.7 on 2020-06-29 14:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(db_index=True, help_text='First Name', max_length=255, unique=True)),
                ('lastname', models.CharField(db_index=True, help_text='Last Name', max_length=255, unique=True)),
                ('dob', models.DateField(db_index=True, help_text='Date of Birth', max_length=255, unique=True)),
                ('department', models.CharField(db_index=True, help_text='Department', max_length=255, unique=True)),
                ('faculty', models.CharField(db_index=True, help_text='Faculty', max_length=255, unique=True)),
                ('university', models.CharField(db_index=True, help_text='University', max_length=255, unique=True)),
                ('graduation_year', models.IntegerField(db_index=True, help_text='Graduation Year', unique=True)),
                ('slug', models.SlugField(blank=True, editable=False, max_length=250, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('student_image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
            options={
                'ordering': ['-created_at'],
                'permissions': (('can_register_certificate', 'Can Register a New Certificate'), ('can_view_ownfaculty_certificates', 'Can View Own Faculty Certificate')),
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='Name')),
                ('email', models.EmailField(db_index=True, max_length=255, unique=True, verbose_name='Email')),
                ('phone', models.CharField(db_index=True, max_length=13, unique=True, verbose_name='Phone')),
                ('message', models.TextField(verbose_name='Message')),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=32, unique=True, verbose_name='Name')),
                ('code', models.CharField(db_index=True, max_length=32, unique=True, verbose_name='code')),
                ('phone', models.CharField(blank=True, max_length=13, null=True, verbose_name='Phone')),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=32, unique=True, verbose_name='Name')),
                ('code', models.CharField(db_index=True, max_length=32, unique=True, verbose_name='code')),
                ('province', models.CharField(max_length=50, verbose_name='province')),
                ('phone', models.CharField(blank=True, max_length=13, null=True, verbose_name='Phone')),
            ],
        ),
        migrations.CreateModel(
            name='UserFacultyRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='faculty', to='generic.Faculty')),
                ('university', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='university', to='generic.University')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UniversityDiplomaDistribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='Name')),
                ('number', models.IntegerField(verbose_name='Diploma Number')),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generic.University', verbose_name='University')),
            ],
        ),
        migrations.AddField(
            model_name='faculty',
            name='university',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='generic.University'),
        ),
        migrations.CreateModel(
            name='Diploma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='Number')),
                ('university', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='generic.University')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='Name')),
                ('code', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='code')),
                ('faculty', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='generic.Faculty')),
                ('university', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='generic.University')),
            ],
        ),
        migrations.CreateModel(
            name='BlankDiploma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(db_index=True, help_text='Barcode', max_length=255, unique=True)),
                ('status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generic.University', verbose_name='University')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
