# Generated by Django 3.0.7 on 2020-07-05 15:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('generic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blankdiploma',
            name='certificate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blank_diploma_certificate', to='generic.Certificate', verbose_name='Certificate'),
        ),
        migrations.AddField(
            model_name='blankdiploma',
            name='user',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blank_diploma_user', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='certificate_status',
            field=models.CharField(choices=[('SUBMITTED', 'SUBMITTED'), ('POSTED', 'POSTED'), ('MAPPED', 'MAPPED')], default='SUBMITTED', max_length=32),
        ),
        migrations.AddField(
            model_name='department',
            name='user',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='department_user', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='faculty',
            name='user',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='faculty_user', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='university',
            name='user',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='university_user', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='universitydiplomadistribution',
            name='user',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='university_distribution_user', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='degree_title',
            field=models.CharField(choices=[('BACHELOR', 'BACHELOR'), ('MASTER', 'MASTER'), ('PHD', 'PHD')], default='BACHELOR', help_text='Degree Title', max_length=255),
        ),
    ]
