# Generated by Django 3.0.7 on 2020-06-29 16:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('generic', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certificate',
            old_name='student_image',
            new_name='picture',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='university',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='universitydiplomadistribution',
            name='name',
        ),
        migrations.AddField(
            model_name='certificate',
            name='birth_year',
            field=models.IntegerField(default=23, help_text='Birth Year'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='certificate',
            name='degree_title',
            field=models.CharField(default=django.utils.timezone.now, help_text='Degree Title', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='certificate',
            name='fathername',
            field=models.CharField(default=django.utils.timezone.now, help_text='Father Name', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='certificate',
            name='gender',
            field=models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], default='MALE', max_length=6),
        ),
        migrations.AddField(
            model_name='certificate',
            name='qrtext',
            field=models.TextField(default=django.utils.timezone.now, editable=False, help_text='QR Code'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='universitydiplomadistribution',
            name='last_no',
            field=models.CharField(blank=True, editable=False, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='blankdiploma',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blank_diploma_university', to='generic.University', verbose_name='University'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificate_department', to='generic.University', verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificate_faculty', to='generic.University', verbose_name='Faculty'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='firstname',
            field=models.CharField(help_text='First Name', max_length=255),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='lastname',
            field=models.CharField(help_text='Last Name', max_length=255),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificate_university', to='generic.University', verbose_name='University'),
        ),
        migrations.AlterField(
            model_name='department',
            name='faculty',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='department_faculty', to='generic.Faculty'),
        ),
        migrations.AlterField(
            model_name='department',
            name='university',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='department_university', to='generic.University'),
        ),
        migrations.AlterField(
            model_name='diploma',
            name='university',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='diploma_university', to='generic.University'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='university',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='faculty_university', to='generic.University'),
        ),
        migrations.AlterField(
            model_name='universitydiplomadistribution',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diploma_distribution_university', to='generic.University', verbose_name='University'),
        ),
        migrations.AlterField(
            model_name='userfacultyrelation',
            name='faculty',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_faculty_relation_faculty', to='generic.Faculty'),
        ),
        migrations.AlterField(
            model_name='userfacultyrelation',
            name='university',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_faculty_relation_university', to='generic.University'),
        ),
    ]
