# Generated by Django 3.0.7 on 2020-06-29 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('generic', '0002_auto_20200629_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificate_department', to='generic.Department', verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificate_faculty', to='generic.Faculty', verbose_name='Faculty'),
        ),
    ]
