# Generated by Django 3.0.7 on 2020-07-05 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('generic', '0002_auto_20200705_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfacultyrelation',
            name='apply_level',
            field=models.CharField(choices=[('SYSTEM', 'SYSTEM'), ('UNIVERSITY', 'UNIVERSITY'), ('FACULTY', 'FACULTY')], default='FACULTY', help_text='User Apply Level', max_length=255),
        ),
        migrations.AlterField(
            model_name='userfacultyrelation',
            name='faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_faculty_relation', to='generic.Faculty'),
        ),
        migrations.AlterField(
            model_name='userfacultyrelation',
            name='university',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_university_relation', to='generic.University'),
        ),
    ]
