# Generated by Django 2.2.5 on 2019-09-05 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(editable=False, max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=512, unique=True),
        ),
        migrations.AlterField(
            model_name='productcateory',
            name='name',
            field=models.CharField(max_length=128, unique=True, verbose_name='Category Name'),
        ),
    ]
