# Generated by Django 2.0.2 on 2020-06-05 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Tenant Name', max_length=255, unique=True)),
                ('code', models.CharField(db_index=True, help_text='Tenant Code', max_length=255, unique=True)),
                ('active', models.BooleanField(default=True, verbose_name='Is Active?')),
            ],
        ),
    ]
