# Generated by Django 2.0.2 on 2020-06-06 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='Office Name')),
                ('code', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='Office Code')),
                ('location', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='Location')),
                ('active', models.BooleanField(default=True, verbose_name='Is Active')),
            ],
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='Office Name')),
                ('template', models.TextField(verbose_name='Template JSON')),
                ('active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('office', models.ForeignKey(on_delete='cascade', to='tenant.Office')),
            ],
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Tenant Name', max_length=255, unique=True)),
                ('code', models.CharField(db_index=True, help_text='Tenant Code', max_length=255, unique=True)),
                ('location', models.CharField(max_length=255, verbose_name='Location')),
                ('active', models.BooleanField(default=True, verbose_name='Is Active?')),
                ('tenant_brand', models.ImageField(upload_to='', verbose_name='Tenant Brand')),
            ],
        ),
        migrations.AddField(
            model_name='office',
            name='tenant',
            field=models.ForeignKey(on_delete='cascade', to='tenant.Tenant'),
        ),
    ]
