# Generated by Django 2.2.4 on 2020-06-07 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Center',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Center Name', max_length=255, unique=True)),
                ('code', models.CharField(db_index=True, help_text='Center Code', max_length=255, unique=True)),
                ('location', models.CharField(max_length=255, verbose_name='Location')),
                ('active', models.BooleanField(default=True, verbose_name='Is Active?')),
                ('tenant', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tenant.Tenant')),
            ],
        ),
        migrations.AddField(
            model_name='template',
            name='center',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tenant.Center'),
        ),
    ]
