# Generated by Django 2.0.2 on 2020-06-05 12:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='tenant_brand',
            field=models.ImageField(default=django.utils.timezone.now, storage='templates/assets/tenants', upload_to='templates/assets/tenants', verbose_name='Tenant Brand'),
            preserve_default=False,
        ),
    ]
