# Generated by Django 2.2.4 on 2020-06-06 07:42

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0002_auto_20200606_0741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='template',
            field=django.contrib.postgres.fields.jsonb.JSONField(),
        ),
    ]
