# Generated by Django 2.0.2 on 2020-06-05 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0002_tenant_tenant_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='tenant_brand',
            field=models.ImageField(upload_to='', verbose_name='Tenant Brand'),
        ),
    ]
