# Generated by Django 2.0.2 on 2020-06-05 16:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0003_auto_20200605_1204'),
    ]

    operations = [
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='Office Name')),
                ('code', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='Office Code')),
                ('location', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='Location')),
                ('active', models.BooleanField(default=True, verbose_name='Is Active')),
            ],
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='Office Name')),
                ('template', models.TextField(verbose_name='Template JSON')),
                ('active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('office', models.ForeignKey(on_delete='cascade', to='tenant.Office')),
            ],
        ),
        migrations.AddField(
            model_name='tenant',
            name='location',
            field=models.CharField(db_index=True, default=django.utils.timezone.now, max_length=255, unique=True, verbose_name='Location'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='office',
            name='tenant',
            field=models.ForeignKey(on_delete='cascade', to='tenant.Tenant'),
        ),
    ]
