# Generated by Django 2.2.4 on 2020-06-07 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0003_auto_20200607_0957'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='center',
            name='location',
        ),
        migrations.AddField(
            model_name='center',
            name='appointments',
            field=models.TextField(blank=True, default=None, editable=False, null=True, verbose_name='Appointments'),
        ),
        migrations.AddField(
            model_name='center',
            name='country',
            field=models.CharField(blank=True, help_text='Country', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='center',
            name='latest_appointment',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Latest Appointment Date'),
        ),
        migrations.AddField(
            model_name='center',
            name='latitude',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Center GIS Latitude'),
        ),
        migrations.AddField(
            model_name='center',
            name='longtitude',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Center GIS Longtitude'),
        ),
        migrations.AddField(
            model_name='center',
            name='province',
            field=models.CharField(blank=True, help_text='Province', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='center',
            name='town',
            field=models.CharField(blank=True, help_text='Town', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='center',
            name='village',
            field=models.CharField(blank=True, help_text='Village', max_length=255, null=True),
        ),
    ]
