# Generated by Django 3.0.7 on 2020-06-06 11:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Form Name', max_length=255, unique=True)),
                ('code', models.CharField(db_index=True, help_text='Form Code', max_length=255, unique=True)),
                ('workflow', models.TextField(db_index=True, help_text='JSON', max_length=2500, unique=True)),
                ('structure', models.TextField(db_index=True, help_text='JSON', max_length=2500, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('slug', models.SlugField(blank=True, editable=False, max_length=250, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenant.Tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Instance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, parent_link=True, related_name='form_instance_relationship', to='form.Form')),
                ('name', models.CharField(db_index=True, help_text='Instance Name', max_length=255, unique=True)),
                ('data', models.TextField(db_index=True, help_text='Data', max_length=2500, unique=True)),
                ('workflow_status', models.CharField(db_index=True, help_text='Workflow Status', max_length=255, unique=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenant.Tenant')),
            ],
        ),
    ]
