# Generated by Django 2.0.2 on 2020-06-05 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0001_initial'),
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form', models.ForeignKey(on_delete='cascade', parent_link=True, related_name='form_instance_relationship', to='form.Form')),
                ('name', models.CharField(db_index=True, help_text='Instance Name', max_length=255, unique=True)),
                ('data', models.TextField(db_index=True, help_text='Data', max_length=2500, unique=True)),
                ('workflow_status', models.CharField(db_index=True, help_text='Workflow Status', max_length=255, unique=True)),
                ('tenant', models.ForeignKey(on_delete='cascade', to='tenant.Tenant')),
            ],
        ),
    ]
