# Generated by Django 2.2.4 on 2020-06-09 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0003_instance_instance_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instance',
            name='instance_no',
            field=models.CharField(blank=True, editable=False, max_length=500, null=True),
        ),
    ]
