# Generated by Django 3.0.7 on 2020-06-28 19:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0004_auto_20200609_0721'),
    ]

    operations = [
        migrations.CreateModel(
            name='Degree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(db_index=True, help_text='First Name', max_length=255, unique=True)),
                ('lastname', models.CharField(db_index=True, help_text='Last Name', max_length=255, unique=True)),
                ('dob', models.DateField(db_index=True, help_text='Date of Birth', max_length=255, unique=True)),
                ('faculty', models.CharField(db_index=True, help_text='Faculty', max_length=255, unique=True)),
                ('university', models.CharField(db_index=True, help_text='University', max_length=255, unique=True)),
                ('graduation_year', models.IntegerField(db_index=True, help_text='Graduation Year', max_length=255, unique=True)),
                ('slug', models.SlugField(blank=True, editable=False, max_length=250, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
