# Generated by Django 3.0.7 on 2020-06-28 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0006_degree_student_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='degree',
            name='student_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
