# Generated by Django 3.0.7 on 2020-06-29 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0008_degree_department'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='degree',
            options={'ordering': ['-created_at'], 'permissions': (('can_register_certificate', 'Can Register a New Certificate'), ('can_view_ownfaculty_certificates', 'Can View Own Faculty Certificate'))},
        ),
    ]
