# Generated by Django 3.0.7 on 2020-06-29 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0009_auto_20200629_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='degree',
            name='graduation_year',
            field=models.IntegerField(db_index=True, help_text='Graduation Year', unique=True),
        ),
    ]
