# Generated by Django 3.0.7 on 2020-06-29 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20200629_0949'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
