# Generated by Django 2.2.5 on 2019-09-05 07:59

import ckeditor_uploader.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='Category Name')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('title', models.CharField(max_length=512, unique=True)),
                ('abstract', models.TextField()),
                ('slug', models.SlugField(editable=False, max_length=250, unique=True)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('category', models.ForeignKey(on_delete='cascade', related_name='project_category', to='project.ProjectCategory')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
